name: Go

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13', '1.12', '1.11' ]
    name: Build with ${{ matrix.go }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Replace imports
      run: sed -i.bak 's+github.com/gomodule/redigo/+github.com/VividCortex/redigo/+' redis/*_test.go redisx/*_test.go

    - name: go get
      run: go get -t -v ./...
      
    - name: go vet
      run: go vet ./...

    - name: go test
      run: go test ./...
